### ISSUE TITLE
Bug: Conversion to QIR

### ISSUE THREAD

**Issue by renezander90** [eclipse-qrisp/Qrisp#199]
```
from pyscf import gto
from qrisp import *
from qrisp.operators import FermionicOperator

mol = gto.M(
    atom = '''
        O     0.0000   0.0000   0.0000
        H     0.7586   0.5840   0.0000
        H    -0.7586   0.5840   0.0000
        ''',
    basis = 'sto-3g')

H = FermionicOperator.from_pyscf(mol)

U = H.trotterization(forward_evolution=False)

# Finding the gound state energy of the Water molecule with QPE
def main():
    qv = QuantumFloat(H.find_minimal_qubit_amount())
    [x(qv[i]) for i in range(10)] # Prepare Hartree-Fock state, H2O molecule has 10 electrons

    qpe_res = QPE(qv,U,precision=20,kwargs={"steps":100})
    phi = measure(qpe_res)
    return phi

jaspr = make_jaspr(main)()
qir_str = jaspr.to_qir()
```

Yields:
> TypeError: _qinst_abstract_eval() got an unexpected keyword argument 'params_len'

**Comment by positr0nium** [comment]
This doesn't produce an error for me - can you ensure that you are on Catalyst 0.11.0?

**Comment by renezander90** [comment]
I was still on Catalyst 0.10.0. It works on 0.11.0.
